In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
torch.manual_seed(1)

In [3]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [7]:
# 모델을 선언 및 초기화. 4개의 특성을 가지고 3개의 클래스로 분류. input_dim=4, output_dim=3.
model = nn.Linear(4, 3)

# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.cross_entropy(prediction, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f} '.format(
            epoch, nb_epochs, cost.item()
        ))
        print(list(model.parameters()))

Epoch    0/1000 Cost: 3.763306 
[Parameter containing:
tensor([[ 0.2622, -0.1124,  0.2844, -0.0074],
        [ 0.0058, -0.3635, -0.0695,  0.4513],
        [-0.1873,  0.2279,  0.0946, -0.3404]], requires_grad=True), Parameter containing:
tensor([-0.3165,  0.3359,  0.1065], requires_grad=True)]
Epoch  100/1000 Cost: 0.634510 
[Parameter containing:
tensor([[-0.8465,  0.0899,  0.5481,  0.0488],
        [-0.0805, -0.3777, -0.0762,  0.5019],
        [ 1.0077,  0.0397, -0.1625, -0.4471]], requires_grad=True), Parameter containing:
tensor([-0.8302, -0.0103,  0.9664], requires_grad=True)]
Epoch  200/1000 Cost: 0.553141 
[Parameter containing:
tensor([[-1.2517, -0.0110,  0.8338,  0.0402],
        [-0.0205, -0.3873, -0.0768,  0.5803],
        [ 1.3528,  0.1502, -0.4476, -0.5169]], requires_grad=True), Parameter containing:
tensor([-1.1150, -0.1979,  1.4388], requires_grad=True)]
Epoch  300/1000 Cost: 0.499127 
[Parameter containing:
tensor([[-1.5523, -0.0825,  1.0959, -0.0202],
        [ 0.0352,

In [9]:
#딥러닝 모델 설계 때 필요한 장비 확인

if torch.cuda.is_available():
    DEVICE = torch.device('cuda') #GPU이용
    
else:
    DEVICE = torch.device('cpu') #GPU이용안되면 CPU이용
    
print('Using PyTorch version:', torch.__version__, ' Device:', DEVICE)

Using PyTorch version: 2.0.1  Device: cuda
