In [2]:
import torch
import numpy as np


In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근
print(t[2:5], t[4:-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0
[2. 3. 4.] [4. 5.]


In [5]:
t= torch.FloatTensor([
    [0.,1.,2.,3.,4.],
    [0.,1.,2.,3.,4.],
    [0.,1.,2.,3.,4.]
])
print(t[0])
print(t[:,1])
print(t[:,1:-1])

tensor([0., 1., 2., 3., 4.])
tensor([1., 1., 1.])
tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])


In [24]:
t = torch.FloatTensor([
    [1,2],
    [3,4]
])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [23]:
t = torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [6,7],
        [8,9]
                ]    
])
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=2))


tensor(5.)
tensor([[3.5000, 4.5000],
        [5.5000, 6.5000]])
tensor([[2., 3.],
        [7., 8.]])
tensor([[1.5000, 3.5000],
        [6.5000, 8.5000]])


In [25]:
t = torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [6,7],
        [8,9]
                ]    
])
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=2))

tensor(40.)
tensor([[ 7.,  9.],
        [11., 13.]])
tensor([[ 4.,  6.],
        [14., 16.]])
tensor([[ 3.,  7.],
        [13., 17.]])


In [33]:
t = torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [6,7],
        [8,9]
                ]    
])
print(t.max())
print(t.max(dim=0)[0])
print(t.max(dim=1)[0])
print(t.max(dim=2)[0])


tensor(9.)
tensor([[6., 7.],
        [8., 9.]])
tensor([[3., 4.],
        [8., 9.]])
tensor([[2., 4.],
        [7., 9.]])


In [3]:
t = torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [6,7],
        [8,9]
                ]    
])
print(t.size())
print(t.shape)
print(t.view([-1,2]))
print(t.view([-1,1,4]))
print(t.view([-1,1,2]))
print(t.view([-1,1,1]))

torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
tensor([[1., 2.],
        [3., 4.],
        [6., 7.],
        [8., 9.]])
tensor([[[1., 2., 3., 4.]],

        [[6., 7., 8., 9.]]])
tensor([[[1., 2.]],

        [[3., 4.]],

        [[6., 7.]],

        [[8., 9.]]])
tensor([[[1.]],

        [[2.]],

        [[3.]],

        [[4.]],

        [[6.]],

        [[7.]],

        [[8.]],

        [[9.]]])


In [6]:
t = torch.FloatTensor([
    [
        [0], 
        [1], 
        [2]
                ],
    [
        [3], 
        [4], 
        [5]
                ]
    ])
print(t.squeeze())

tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [7]:
t=torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [1,2],
        [3,4]
                ]    
])
print(t.unsqueeze(0))
print(t.unsqueeze(1))
print(t.unsqueeze(2))
print(t.unsqueeze(3))

tensor([[[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]]])
tensor([[[[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]]]])
tensor([[[[1., 2.]],

         [[3., 4.]]],


        [[[1., 2.]],

         [[3., 4.]]]])
tensor([[[[1.],
          [2.]],

         [[3.],
          [4.]]],


        [[[1.],
          [2.]],

         [[3.],
          [4.]]]])


In [77]:
x = torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [6,7],
        [8,9]
                ]    
])
y = torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [6,7],
        [8,9]
                ]    
])
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))
print(torch.cat([x, y], dim=2))

tensor([[[1., 2.],
         [3., 4.]],

        [[6., 7.],
         [8., 9.]],

        [[1., 2.],
         [3., 4.]],

        [[6., 7.],
         [8., 9.]]])
tensor([[[1., 2.],
         [3., 4.],
         [1., 2.],
         [3., 4.]],

        [[6., 7.],
         [8., 9.],
         [6., 7.],
         [8., 9.]]])
tensor([[[1., 2., 1., 2.],
         [3., 4., 3., 4.]],

        [[6., 7., 6., 7.],
         [8., 9., 8., 9.]]])


In [8]:
x = torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [6,7],
        [8,9]
                ]    
])
y = torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [6,7],
        [8,9]
                ]    
])
z = torch.FloatTensor([
    [
        [1,2],
        [3,4]
                ],
    [
        [6,7],
        [8,9]
                ]    
])
print(torch.stack([x, y, z],dim=0))
print(torch.stack([x, y, z],dim=1))


tensor([[[[1., 2.],
          [3., 4.]],

         [[6., 7.],
          [8., 9.]]],


        [[[1., 2.],
          [3., 4.]],

         [[6., 7.],
          [8., 9.]]],


        [[[1., 2.],
          [3., 4.]],

         [[6., 7.],
          [8., 9.]]]])
tensor([[[[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]],

         [[1., 2.],
          [3., 4.]]],


        [[[6., 7.],
          [8., 9.]],

         [[6., 7.],
          [8., 9.]],

         [[6., 7.],
          [8., 9.]]]])


In [91]:
print(torch.stack([x, y, z],dim=2))
print(torch.stack([x, y, z],dim=3))

tensor([[[[1., 2.],
          [1., 2.],
          [1., 2.]],

         [[3., 4.],
          [3., 4.],
          [3., 4.]]],


        [[[6., 7.],
          [6., 7.],
          [6., 7.]],

         [[8., 9.],
          [8., 9.],
          [8., 9.]]]])
tensor([[[[1., 1., 1.],
          [2., 2., 2.]],

         [[3., 3., 3.],
          [4., 4., 4.]]],


        [[[6., 6., 6.],
          [7., 7., 7.]],

         [[8., 8., 8.],
          [9., 9., 9.]]]])
